### ISSUE TITLE
Plugin Causes app to crash under Android L (5.0)

### ISSUE THREAD

**Issue by ctampak** [m1is/AviaryCordovaPlugin#14]
I have used the plugin for a cordova based app and it works great under both android and iOS until today. 

I received a crash report by a user that uses a nexus 5 updated to Android 5.0.1. I was able to reproduce the problem and I think the issue will be resolved if the plugin is updated to the latest Aviary version.

I was wondering if there is an update path to the latest SDK?
Thanks in advance

**Comment by m1is** [comment]
This plugin was built to work with Aviary SDK version 3.0 which doesn’t run on Android 5.  I heard that the latest version of the SDK will now run on Android 5 but it’s now an Adobe product and I haven’t had a chance yet to check it out.
