### ISSUE TITLE
Aviary photo editor does not appear on iOS7

### ISSUE THREAD

**Issue by SeanStewart37** [m1is/AviaryCordovaPlugin#3]
Once I retrieve the photo URI and send it to Aviary, I get the following warning:

 Warning: Attempt to present <AFSDKViewController: 0xce7ebe0> on <MainViewController: 0xbf4bf40> while a presentation is in progress!

The Editor does not appear.  I don't get this issue with iOS6 with the same code.

**Comment by SeanStewart37** [comment]
So after diving into the code, I saw you are putting a 500ms delay.  Changing it to 1000ms resolves this issue. Unfortunately it's a longer delay.

**Comment by m1is** [comment]
Thanks for your feedback, if you ever determine the proper way to launch the editor without the delay hack please let me know.

**Comment by SeanStewart37** [comment]
I'm working on it.  I found this but it doesn't seem to fix it. Anyways, great plugin. http://stackoverflow.com/questions/15874094/presentmodalviewcontrolleranimated-is-deprecated-in-ios6

This may also have a factor, but I don't know how to get the initial app reference to hide it before bringing up Aviary.
http://stackoverflow.com/questions/14453001/meaning-of-warning-while-a-presentation-is-in-progress

**Comment by SeanStewart37** [comment]
Dated issue. Closing
