### ISSUE TITLE
Quality argument not handled properly in iOS

### ISSUE THREAD

**Issue by danieldkim** [m1is/AviaryCordovaPlugin#5]
The iOS plugin is passing the `compressionQuality` argument to the [`UIImageJPEGRepresentation`](https://developer.apple.com/library/ios/documentation/uikit/reference/UIKitFunctionReference/Reference/reference.html#//apple_ref/c/func/UIImageJPEGRepresentation) constructor incorrectly.

"The quality of the resulting JPEG image, expressed as a value from 0.0 to 1.0. The value 0.0 represents the maximum compression (or lowest quality) while the value 1.0 represents the least compression (or best quality)."

**Comment by m1is** [comment]
Thank you for catching that as I am not very experienced with iOS.

**Comment by danieldkim** [comment]
No problem.  I'm not an expert in iOS but noticed that the output images were much larger than they should be if compression were working properly.
